spring:
  datasource:
    url: jdbc:h2:mem:foundation_database;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: "root"
    password: "abcd1234"
    platform: h2
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
    default_schema: foundation_database

mybatis-plus:
  map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/mapper/**.xml
#  global-config:
#    db-config:
#      logic-delete-field: is_del
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com:
      example:
        mapper: DEBUG