spring:
  datasource:
    url: jdbc:h2:mem:foundation_database;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: "root"
    password: "abcd1234"
    platform: h2
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
    default_schema: foundation_database